apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: kiali-traffic-generator
  labels:
    app: kiali-traffic-generator
    kiali-test: traffic-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kiali-traffic-generator
      kiali-test: traffic-generator
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        app: kiali-traffic-generator
        kiali-test: traffic-generator
        istio.io/dataplane-mode: "none"
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - image: quay.io/kiali/kiali-test-mesh-traffic-generator:latest
        name: kiali-traffic-generator
        imagePullPolicy: IfNotPresent
        env:
        - name: DURATION
          valueFrom:
            configMapKeyRef:
              name: traffic-generator-config
              key: duration

        - name: ROUTE
          valueFrom:
            configMapKeyRef:
              name: traffic-generator-config
              key: route

        - name: RATE
          valueFrom:
            configMapKeyRef:
              name: traffic-generator-config
              key: rate
        - name: SILENT
          valueFrom:
            configMapKeyRef:
              name: traffic-generator-config
              key: silent
